humalien/humalien/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('vision/',include('vision.urls')),
]

humalien/vision/urls.py
from django.urls import path, re_path
from . import views
#namespace
app_name = 'vision'
urlpatterns = [
    path('create/', views.TaskCreateView.as_view(), name='task_create'),
    path('', views.TaskListView.as_view(), name='task_list'),
    #retrive single task object
    re_path(r'^(?P<pk>\d+)/$', views.TaskDetailView.as_view(),name='task_detail'),
            
    re_path(r'^(?P<pk>\d+)/update/$', views.TaskUpdateView.as_view(),name='task_update'),
            
    re_path(r'^(?P<pk>\d+)/delete/$', views.TaskDeleteView.as_view(),name='task_delete'),
]         

humalien/vision/models.py
from django.db import models

# Create your models here.

class noise(models.TextChoices):
   undo='U',"Not yet Started"
   on='O',"ONGOING"
   done='D',"DONE"

class dmt(models.Model):
   name=models.CharField(verbose_name="Task name",max_length=65,unique=True)
   status=models.CharField(verbose_name="Task status",max_length=10,choices=noise.choices)

def _mint_(self):
   return self.name

humalien/vision/forms.py
from .models import dmt
from django import forms

class sony(forms.ModelForm):
   
   class Meta:
      model=dmt
      fields='__all__'

humalien/vision/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.urls import reverse,reverse_lazy
from .models import dmt
from .forms import sony

from django.views.generic import ListView,DetailView,\
     CreateView,UpdateView,DeleteView

class TaskListView(ListView):
   model=dmt
   context_object_name='vision'
   
class TaskDetailView(DetailView):
   model=dmt
class TaskCreateView(CreateView):
   model=dmt
   form_class = sony
   success_url = reverse_lazy('vision:task_list')
   
class TaskUpdateView(UpdateView):
   model=dmt
   form_class = sony
   success_url = reverse_lazy('vision:task_list')

class TaskDeleteView(DeleteView):
   model= dmt
   success_url = reverse_lazy('vision:task_list')
   

humalien/vision/templates/vision/dmt_confirm_delete.html
<!DOCTYPE html>
<form method="post"> {% csrf_token %}
	<p>U want to delete it completly "{{task}}"?</p>
	<input type="submit" name="Confirm">	
</form>

humalien/vision/templates/vision/dmt_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Task Detail</title>
</head>
<body>
<p> Task Name: {{ task.name }} | <a href="{% url 'vision:task_update' task.id %}">Update</a> |
    <a href="{% url 'vision:task_delete' task.id %}">Delete</a>
</p>
<p> Task Status: {{ task.get_status_display }} </p>
<p> <a href="{% url 'vision:dmt_list' %}">View All Tasks</a> |
    <a href="{% url 'vision:task_create' %}">New Task</a>
</p>
</body>
</html>

humalien/vision/templates/vision/dmt_form.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>{%if object%}Edit Task{%else%} Create New Task{%endif%}</title>
</head>
<body>
	<h3>{%if object%}Edit Task{% else %} Create New Task{% endif%}</h3>
	   <form action="" method="post" enctype="multipart/form-data">
	   	{%csrf_token%}
	   	{{form.as_p}}
	   	<p><input type="submit" class="btn btn-success" value="SUBMIT"></p>
	   	
	   </form>

</body>
</html>

humalien/vision/templates/vision/dmt_list.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>Task list</title>
</head>
<body>
	 <h3>Task list</h3>
	 {%for task in vision%}
	 <p>{{forloop.counter}}.{{task.name}}-{{task.get_status_display}}
	            (<a href="{% url 'vision:task_update' task.id %}">UPDATE</a>|
	             <a href="{% url 'vision:task_delete' task.id %}">DELETE</a>)
	  </p>
	  {% endfor %}
	  <p><a href="{% url 'vision:task_create' %}">+ADD UP YOUR TASK</a></p>

</body>
</html>